services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery_worker:
    build: ./src
    command: celery -A config worker -l info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # backend:
  #   build: ./src
  #   ports:
  #     - "8000:8000"  
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./src:/app  
  #   command: sh -c "sleep 2 && \
  #                 python manage.py migrate --fake && \
  #                 python manage.py makemigrations && \
  #                 python manage.py migrate && \
  #                 python manage.py runserver 0.0.0.0:8000"
  #   depends_on:
  #     - redis
  #     - celery_worker
    
