# Generated by Django 5.1.7 on 2025-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan_speed',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='time')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('serverroom_temperature', models.CharField(max_length=50, verbose_name='serverroom_temperature')),
                ('softwareroom_temperature', models.CharField(max_length=50, verbose_name='softwareroom_temperature')),
                ('serverroom_humidity', models.CharField(max_length=50, verbose_name='serverroom_humidity')),
            ],
        ),
    ]
